### ISSUE TITLE
Backup Profiles docs for Digital Ocean Spaces outdated?

### ISSUE THREAD

**Issue by squpshift** [cleavr/cleaverdocs#13]
Hey :)

The way digital ocean spaces connection profiles need to be configured in app.cleavr.io appears to have changed.

I had to change the ORIGIN URL value from `https://mybucket.sgp1.digitaloceanspaces.com` to `https://sgp1.digitaloceanspaces.com`, and enter `mybucket` into the BUCKET field.

https://github.com/cleavr/cleaverdocs/blob/master/content/documentation/backup-profiles.md

**Comment by armgitaar** [comment]
Thanks for pointing it out! I've made an update to clarify what the origin url should look like.
