### ISSUE TITLE
Directus docs out of date

### ISSUE THREAD

**Issue by connor11528** [cleavr/cleaverdocs#15]
Hi there,

First off I want to say thanks you are by far the easiest way to deploy Directus to the cloud! I wanted to share a couple notes having just set up a server and being new to directus and your platform.

- Step 1 connect your VPS account. This is missing from the docs. I ran into a permissions error when trying to set up a custom server then gave up and switched to Digital Ocean where I had to search how to create a personal access token in their UI. Some guidance about this on the [directus doc](https://github.com/cleavr/cleaverdocs/blob/master/content/guides/directus.md) would be nice!
- Step 3: I no longer had to select any GitHub repo or anything so that part may be out of date..
- Step 4: How do I login to my Directus site? I created a MySQL database with the admin and password but not clear how to get into my Directus instance. I'm now seeing more docs on the [github repo](https://github.com/cleavr/directus-example) mentioned in the article but it would be nice to have it in the docs too.

Overall totally bravo and I'm sure I'll be into this soon! I do think improving this doc with more content will help it rank higher because it definitely should be the #1 or #2 search result for "self host directus"

**Comment by connor11528** [comment]
Not really sure how to check the "build asset" logs.. maybe that has been renamed?

```
After deployment, check the Build Assets logs
```

**Comment by connor11528** [comment]
Okay I'm dumb it says in the UI the admin email and the admin password.

**Comment by rabinkmc** [comment]
We really appreciate and thank you, @connor11528, for taking the time to share your experience and for providing us with such detailed feedback. We have taken note of your suggestion and we will definitely update our docs accordingly.

Also, we would love for you to join our forum community at https://forum.cleavr.io/.
