### ISSUE TITLE
Oracle region code is unclear

### ISSUE THREAD

**Issue by jdevine** [cleavr/cleaverdocs#9]
In the instructions for setting up a vps profile for Oracle https://docs.cleavr.io/vps-profiles/ no mention is made of the required field "region code".

I attempted to paste in the region code listed in my Oracle account "US East (Ashburn)", and it was rejected as invalid. 

No mention of it is made in the instructions.

A related issue is that navigating away from the dashboard page after clicking "add a VPS profile", the form disappears and the entries are cleared. So filling out that form, copying values from another document or browser tab, is very trying. I have given up for the evening, possibly forever.

**Comment by armgitaar** [comment]
@jdevine thanks for pointing that out! 

I've updated the docs. Easiest way to find the region identifier is via the Oracle Cloud URL when your signed into your account.
